---
title: "EEMs Spectra Summary"
subtitle: "Template"
author: "Emily Taylor"
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{placeins}
  - \usepackage{subfig}
  - \usepackage{booktabs}
  - extra_dependencies: subfig
output:
  html_notebook: default
  html_document: 
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
  pdf_document:
    fig_crop: yes
    toc: true
    number_sections: true
    extra_dependencies: subfig
geometry: margin = 0.75in
editor_options:
  markdown:
    wrap: 80
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,  
                      warning = FALSE,
                      cache = FALSE,
                      # results = 'hide',
                      dev = "CairoPNG", 
                      comment = '#>',
                      fig.path = "~/Projects/Ch2_DOM/figures/5_summary-tables/"
                      )

# this essentially places "\FloatBarrier\" at the end of every figure to prevent figures migrating throughout a document
knitr::knit_hooks$set(plot = function(x, options) {
  paste0(knitr::hook_plot_tex(x, options), "\n\\FloatBarrier\n")
})
```

```{r library, include = FALSE}
librarian::shelf(
  tidyr,
  dplyr,
  ggplot2,
  imputeTS,
  plotly,
  timetk,
  lubridate,
  patchwork,
  hrbrthemes, 
  flextable, 
  kableExtra
)
```

```{r functions, include = FALSE}
source("~/Projects/Ch2_DOM/scripts/functions/figure-options.R")

source("~/Projects/Ch2_DOM/scripts/functions/labeled_eems.R")
```

```{r load-data}
data <- 
  readRDS("~/Projects/Ch2_DOM/output/ch2_eem_index_20230711.rds")

abs_slope <- 
  readRDS("~/Projects/Ch2_DOM/output/ch2_absorbance_slopes_20230711.rds")

comps <- 
  readRDS("~/Projects/Ch2_DOM/output/ch2_PARAFAC_sample-loading_2023-07-17.rds")
```

```{r add-date-breakdown-columns, echo = FALSE, include = FALSE}

data$date <- ymd(data$date)

data$month <- month(data$date, label = TRUE, abbr = TRUE)

data$year <- year(data$date)

data$quarter <- quarter(data$date)

```

```{r add-stream-names}

## Reordering data$site
data$site <- data$site %>%
  forcats::fct_relevel(
    "HAT", "HOGDN", "POS", "HOGUP", "SWBUP", "SWB", "TUM"
  )

## Recoding data$site into data$site_rec
data$stream <- data$site %>%
  forcats::fct_recode(
    "Hatchet" = "HAT",
    "S. Hogtown" = "HOGDN",
    "N. Hogtown" = "HOGUP",
    "Possum" = "POS",
    "Sweetwater" = "SWB",
    "N. Sweetwater" = "SWBUP",
    "Tumblin" = "TUM"
  )


# site_count 
data %>% 
  group_by(stream) %>% 
  count(stream)

```


## Modeled Days
```{r count-modeled-days}
qt <- knitr::kable(data %>% 
  group_by(stream) %>% 
  count(stream), 
  col.names = c("Site", "Modeled Days"), 
  align = c('l', 'c'), 
  booktabs = T) %>% 
  row_spec(row = 0, 
           bold = TRUE) %>% 
  kable_styling(bootstrap_options = c("condensed"), 
                full_width = F, 
                latex_options = c("hold_position"),
                font_size = 12)

qt
```

```{r annual-modeled-day-count}

wider <- data %>%
  select(c(stream, date, year, fi_cor)) %>%
  pivot_longer(cols = 4,
               names_to = "fi_cor",
               values_to = "value") %>%
  group_by(stream, year) %>%
  count(fi_cor) %>%
  select(-c(fi_cor))

wider <- wider %>%
  pivot_wider(names_from = "year", values_from = "n")


yt <- knitr::kable(wider,
  col.names = c("Site", "2019", "2020", "2021", "2022"), 
  align = c('l', 'c', 'c', 'c', 'c'), 
  booktabs = T) %>%
  kable_styling(bootstrap_options = c("condensed"), 
                full_width = F, 
                latex_options = c("hold_position"),
                font_size = 12) %>% 
  row_spec(row = 0, 
           bold = TRUE) %>% 
  add_header_above(c("", "Number of Days Modeled" = 4), 
                   bold = TRUE)

yt

```
## EEM Index Summary
```{r summarise-gpp, message = FALSE}
monthly.avg.gpp <- data %>%
  dplyr::select(c(stream, month, a, b, c, t, m, fi_cor, bix, hix)) %>%
  group_by(stream, month) %>%
  summarise(a = mean(a),
            b = mean(b),
            c = mean(c), 
            t = mean(t),
            m = mean(m),
            fi = mean(fi_cor), 
            bix = mean(bix),
            hix = mean(hix)
            )

annual.avg.gpp <- data %>%
  dplyr::select(c(stream, year, a, b, c, t, m, fi_cor, bix, hix)) %>%
  group_by(stream, year) %>%
  summarise(a = mean(a),
            b = mean(b),
            c = mean(c), 
            t = mean(t),
            m = mean(m),
            fi = mean(fi_cor), 
            bix = mean(bix),
            hix = mean(hix)
            )

quarterly.avg.gpp <- data %>%
  dplyr::select(c(stream, quarter, a, b, c, t, m, fi_cor, bix, hix)) %>%
  group_by(stream, quarter) %>%
  summarise(a = mean(a),
            b = mean(b),
            c = mean(c), 
            t = mean(t),
            m = mean(m),
            fi = mean(fi_cor), 
            bix = mean(bix),
            hix = mean(hix)
            )

```

```{r annual-gpp-table, message = FALSE}
annual.avg.gpp %>% 
  knitr::kable(
    col.names = c("Site", "Year", "a", "b", "c", "t", "m", "FI", "BIX", "HIX"), 
    align = c("l", "l", "c", "c", "c", "c", "c", "c", "c", "c"), 
    digits = 2, 
    booktabs = T) %>% 
  row_spec(row = 0, 
           bold = TRUE) %>% 
  kable_styling(bootstrap_options = c("condensed"), 
                full_width = F, 
                font_size = 12, 
                latex_options = c("scale_down", "hold_postion")) %>% 
  add_header_above(c("", "", "Coble Peaks" = 5, "EEM Index" = 3), 
                   bold = TRUE)

```

```{r quarterly-coble-table, message = FALSE}
quarterly.avg.gpp %>%
  knitr::kable(
    col.names = c("Site", "Quarter", "a", "b", "c", "t", "m", "FI", "BIX", "HIX"),
    align = c("l", "l", "c", "c", "c", "c", "c", "c", "c", "c"),
    digits = 2,
    booktabs = T
  ) %>%
  kable_styling(
    bootstrap_options = c("condensed"),
    full_width = F,
    font_size = 12,
    latex_options = c("scale_down", "hold_postion")
  ) %>%
 add_header_above(c("", "", "Coble Peaks" = 5, "EEM Index" = 3), 
                   bold = TRUE) 
```

```{r peak-a}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = a, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = a),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Peak A") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```

```{r peak-b}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = b, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = b),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Peak B") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```

```{r peak-c}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = c, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = c),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Peak C") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```

```{r peak-t}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = t, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = t),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Peak T") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```

```{r peak-m}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = m, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = m),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Peak M") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```


```{r fi-corr}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = fi_cor, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = fi_cor),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Fluoresence Index") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```


```{r bix}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = bix, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = bix),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Biological Index") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```

```{r hix}
ggplot(data) + # set data to NULL if you want to use 2 different data sets
  geom_boxplot(aes(x = stream, 
                   y = hix, 
                   fill = stream), 
               outlier.shape = NA) + 
  geom_point(data, 
             mapping = aes(x = stream, 
                           y = hix),
             position = position_jitter(height = 0, width = 0.2), alpha = 0.05, size = 2) +
  scale_fill_manual(values = sitcol, 
                    labels = sitlabs) + 
   scale_x_discrete(labels = sitlabs) +
  ylab("Humification Index") +
  # labs(caption = "Period of Record: February 2019 - December 2021") +
  emily_2var_theme
```

------------------------------------------------------------------------

## Absorbance Summary

```{r absorbance-spectra-plots, fig.height = 10, fig.width = 14}

# load abs data -----------------------------------------------------------

absorbance_path <-
  "~/Projects/Ch2_DOM/processed-data/abs-for-analysis"

absorbance <-
  staRdom::absorbance_read(absorbance_path, recursive = T)

# clean up absorbance -----------------------------------------------------

absorbance <-
  staRdom::abs_blcor(absorbance, wlrange = c(680, 700))

absorbance <-
  absorbance %>%
  tidyr::pivot_longer(
    cols = !wavelength,
    names_to = "sample",
    values_to = "abs"
  ) %>%
  filter(wavelength > 245 & wavelength < 750)


# fix abs sample names ---------------------------------------------

absorbance$sampleid <- 
  stringr::str_extract(absorbance$sample, "([B]\\d+S\\d{1,2})")

absorbance$site_ID <- 
  stringr::str_extract(absorbance$sample, "(Blank1|Blank2|Blank3|Blank4|Blank5|HAT|HOGDN|HOGUP|POS|SWBUP|SWB|TUM)")

absorbance$date <- 
  stringr::str_extract(absorbance$sample, "(?<=_)(\\d{4})[[:alpha:]]\\w+\\d{2}")

blank_list <- c("Blank1", "Blank2", "Blank3", "Blank4", "Blank5")

absorbance <- absorbance %>% dplyr::filter(!site_ID %in% blank_list)

dilution_list <- c("B1S7_HAT_2019Feb20",                   "B1S10_HOGUP_2019Aug14",
                   "B1S11_HAT_2019Apr03" ,                   "B1S4_HAT_2019Apr24" ,
                   "B1S1_HAT_2019May07" ,                   "B1S4_HAT_2019May07" ,
                   "B1S7_HAT_2019May24" ,                   "B1S11_HAT_2019Jun18",
                   "B1S4_HAT_2019Jun06" ,                   "B1S4_HAT_2019Jul09" ,
                   "B1S10HOGUP_2019Aug14",                   "B2S21_HAT_2019Oct09" ,
                   "B1S7_HAT_2019Aug14" ,                   "B1S7_HAT_2019Sept11" ,
                   "B1S10_HOGUP_2019Aug28",                   "B1S14_HAT_2019Sept25" ,
                   "B1S7_HAT_2019Aug28" ,                   "B1S7_HAT_2019Oct23" ,
                   "B1S7_HAT_2019Nov06" ,                   "B1S13_HAT_2019Dec17" ,
                   "B1S6_HAT_2019Nov20" ,                   "B1S6_HAT_2020Jan10" ,
                   "B1S15_HAT_2020Mar12" ,                   "B1S8_HAT_2020Feb28" ,
                   "B1S8_HAT_2020Jun26" ,                   "B1S8_HAT_2020Jul16" ,
                   "B1S8_HAT_2020Jul28" ,                   "B1S8_HAT_2020Aug14" ,
                   "B1S11_HAT_2020Aug25_dil",                   "B1S8_HAT_2020Aug25" ,
                   "B1S11_HAT_2020Sept10_dil",                   "B1S8_HAT_2020Sept10" ,
                   "B1S9_HOGUP_2020Sept10",                   "B2S16_HAT_2020Sept25" ,
                   "B2S17_HOGUP_2020Sept25",                   "B2S19_HAT_2020Sept25_dil" ,
                   "B1S13_HAT_2021Mar08" ,                   "B1S14_HAT_2021Mar08_dil2" ,
                   "B1S15_HAT_2021Mar08_dil3" ,                   "B1S4_HAT_2021Feb08" ,
                   "B1S6_HAT_2021Feb08_dil3" ,                   "B1S10_HAT_2021May04_dil3" ,
                   "B1S8_HAT_2021May04" ,                   "B2S16_HAT_2021May17" ,
                   "B2S18_HAT_2021May17_dil3" ,                   "B1S8_HAT_2021Jun01" ,
                   "B2S16_HAT_2021Jun21" ,                   "B2S17_HAT_2021Jun21_dil2" ,
                   "B1S10_HAT_2021Jul06_dil3" ,                   "B1S12_POS_2021Jul06" ,
                   "B1S4_HOGUP_2021Jul06" ,                   "B1S5_HOGDN_2021Jul06" ,
                   "B1S8_HAT_2021Jul06" ,                   "B1S9_HAT_2021Jul06_dil2" ,
                   "B2S16_HAT_2021Jul20" ,                   "B2S17_HAT_2021Jul20_dil2" ,
                   "B1S8_HAT_2021Aug25" ,                   "B1S9_HAT_2021Aug25_dil2" ,
                   "B2S16_HAT_2021Sep08" ,                   "B2S17_HAT_2021Sep08_dil2" ,
                   "B1S4_HOGDN_2021Sept22" ,                   "B2S20_HOGUP_2021Sept22" ,
                   "B1S2_HAT_2021Sept22" ,                   "B1S3_HAT_2021Oct02" ,
                   "B1S4_HAT_2021Oct20" ,                   "B2S10_SWBUP_2021Sept22" ,
                   "B2S5_HAT_2021Nov03" ,                   "B2S6_HAT_2021Nov17" ,
                   "B2S7_HAT_2021Dec01" ,                   "B2S8_HAT_2021Dec15" ,
                   "B2S9_HAT_2022Jan12", "B1S9_HAT_2021Jun01_dil2")

absorbance <- absorbance %>% dplyr::filter(!sample %in% dilution_list)

date_list <- c("2020Jan24")

absorbance <- absorbance %>% dplyr::filter(!date %in% date_list)

# plot absorbance spectra -----------------------------------------------------

library(ggspectra)

ggplot(absorbance, 
       plot.qty = "absorbance") +
  geom_line(aes(x = wavelength, 
            y = abs, 
            color = site_ID)) +
  scale_x_wl_continuous() +
  scale_y_A_total_continuous() +
  facet_wrap(facets = vars(date), 
             scales = "free_y")


```

------------------------------------------------------------------------

## Component Summary

```{r comp-plots}

librarian::shelf(
  tidyr,
  dplyr)
  
pf_final <- readRDS("~/Projects/Ch2_DOM/output/5-comp-final-model_2023-07-16.rds")

mc <- function(pfmodel)
{
  mat <- 
    lapply(seq(1:ncol(pfmodel$A)),
                function(comp) {
                 list(
                   value = matrix(pfmodel$B[, comp]) %*%
                    t(matrix(pfmodel$C[, comp])) ,
                  ex = pfmodel$C %>% rownames(),
                  em = pfmodel$B %>% rownames(),
                  sample = paste(comp)
                 )
                })
   # mat
}

pfm <- mc(pf_final[[1]])

comp1_labeled_plots(pfm)

comp2_labeled_plots(pfm)

comp3_labeled_plots(pfm)

comp4_labeled_plots(pfm)

comp5_labeled_plots(pfm)

```

